- name: Upload frontend to Azure Blob Storage
  uses: azure/cli@v1
  with:
    inlineScript: |
      # Login to Azure using a service principal
      az login --service-principal --username "${{ secrets.AZURE_CLIENT_ID }}" --password "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}"

      # Print current directory
      echo "Current directory: $(pwd)"
      
      # Change into the frontend directory
      cd frontend

      # List contents for debug
      echo "Uploading these files:"
      ls -al

      # Upload frontend contents using login-based auth (requires SP to have 'Storage Blob Data Contributor' role)
      az storage blob upload-batch --account-name raresonalcloudresume --destination '$web' --source . --pattern "*" --auth-mode login
