name: Deploy Frontend to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload frontend to Azure Blob Storage
        uses: azure/cli@v1
        with:
          inlineScript: |
            # Login to Azure using a service principal
            az login --service-principal --username "${{ secrets.AZURE_CLIENT_ID }}" --password "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}"

            echo "Current directory:"
            pwd

            echo "List contents of repository:"
            ls -R

            # Change to the frontend directory
            cd frontend

            echo "List contents of the frontend directory:"
            ls -R

            # Upload frontend contents to $web container with full paths
            az storage blob upload-batch \
              --account-name raresonalcloudresume \
              --destination '$web' \
              --source $(pwd) \
              --pattern "*" \
              --auth-mode key \
              --account-key "${{ secrets.AZURE_STORAGE_KEY }}"
