- name: Upload frontend to Azure Blob Storage
  uses: azure/cli@v1
  with:
    inlineScript: |
      # Login to Azure using a service principal
      az login --service-principal --username "${{ secrets.AZURE_CLIENT_ID }}" --password "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}"

      # Debug Azure Storage Account
      echo "Testing Azure Storage Connection"
      az storage account show --name raresonalcloudresume --auth-mode key --account-key "${{ secrets.AZURE_STORAGE_KEY }}"

      # Upload frontend contents
      az storage blob upload-batch --account-name raresonalcloudresume --destination '$web' --source $(pwd) --pattern "*" --auth-mode key --account-key "${{ secrets.AZURE_STORAGE_KEY }}"
