# GitHub Action to deploy frontend to Azure Blob Storage ($web)
# Uses Service Principal with RBAC (Storage Blob Data Contributor)

name: Deploy frontend to Azure Blob Storage - raresonalcloudresume

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files for debug
        run: ls -R

      - name: Set up Azure CLI
        uses: azure/cli@v1
        with:
          inlineScript: |
            echo "Logging in to Azure..."
            az login --service-principal \
              --username "${{ secrets.AZURE_CLIENT_ID }}" \
              --password "${{ secrets.AZURE_CLIENT_SECRET }}" \
              --tenant "${{ secrets.AZURE_TENANT_ID }}"

            echo "Changing to frontend directory..."
            cd frontend

            echo "Listing frontend directory contents:"
            ls -al

            echo "Uploading to Azure Blob Storage..."
            az storage blob upload-batch \
              --account-name raresonalcloudresume \
              --destination '$web' \
              --source . \
              --pattern "*" \
              --auth-mode login \
              --overwrite true
